### ISSUE TITLE
player not getting picked up by storms

### ISSUE THREAD

**Issue by Jaytv25** [Mrbt0907/Weather2-Remastered#54] opened 2022-05-24 16:28 UTC
bug report: for some reason when i found a tornado i went to it and nothing happened same thing happened with the hurricane and even in their stronger stages they still cannot pick anything that is a player up

**Comment by Mrbt0907** [comment] 2022-05-25 16:00
Please check your grab settings either in the EZ Gui **and** in the advanced configuration under ConfigGrab. Players should be enabled. If this option is enabled in both menus and the problem persists, please report back here. There may be a desync issue when it comes to the EZ Gui.

**Comment by Jaytv25** [comment] 2022-05-25 23:05
i just checked and it was on

**Comment by Mrbt0907** [comment] 2022-05-26 05:55
If you are in creative mode, then you can't be picked up. If you are in survival mode, then it is something else that I don't know about. If so, I need you to post the configs and the list of mods so I can reproduce this bug. I don't need the mod files, just the mod names.

**Comment by Dovahkiin-Warrior** [comment] 2022-05-26 17:19
![image](https://user-images.githubusercontent.com/16886014/170541090-cd83bb19-70a9-4682-8d99-f9b84dd1f518.png)

Sorry @Jaytv25 I am unable to confirm your bug...

**Comment by Jaytv25** [comment] 2022-05-26 18:46
i did "try going into singleplayer on a superflat map, and using /storm create f1 ~ ~ while in survival"
and even then it did not work

**Comment by Mrbt0907** [comment] 2022-05-26 19:21
Please send me the log and delete the mod's configs to see if that fixes your issue. I need to see what's going on.

**Comment by Jaytv25** [comment] 2022-05-26 20:00
I think it might be because of a specific version of coroutil

**Comment by Dovahkiin-Warrior** [comment] 2022-05-26 21:21
> I think it might be because of a specific version of coroutil

I'm using coroutil-1.12.1-1.2.37.jar for my testing. Please keep in mind we have no control over coroutil dependencies at this point in time. I recommend using this version for now or until @Mrbt0907 says otherwise ^^

**Comment by Jaytv25** [comment] 2022-06-01 18:06
btw the glitch does not happen in the original weather 2

**Comment by Jaytv25** [comment] 2022-06-02 01:13
That was the version I was using

**Comment by Dovahkiin-Warrior** [comment] 2022-06-02 01:33
> BTW the only mods I had were weather 2 remastered and coroutil 1.2.36

Which version of weather 2 remastered? If the [latest version](https://github.com/Mrbt0907/Weather2-Remastered/releases/download/2.7.7-alpha-1.12.2/Weather2Remastered-1.12.2-2.7.7-alpha.jar) (2.7.7 alpha at this point in time) has the issue, please try deleting the config files and reloading your game.

**Comment by Dovahkiin-Warrior** [comment] 2022-06-02 01:36
> That was the version I was using


Also, please try with [coroutil 1.12.1-1.2.37] (https://www.curseforge.com/minecraft/mc-mods/coroutil/download/2902920).

**Comment by Mrbt0907** [comment] 2022-06-02 03:43
This is leaving me stumped. Please try to run the mod with the configs cleared and with the latest forge version for 1.12.2. 

If that fails, then I don't know what else could be causing the issue.

**Comment by Mrbt0907** [comment] 2022-06-04 22:18
I think this issue pertains to the ghosting issue I have been getting in my dev environment. What is likely happening is the storms aren't real and therefore won't pick you up. If that is the issue, then I should have it fixed by next update.

**Comment by Jaytv25** [comment] 2022-06-06 03:03
ok

**Comment by Jaytv25** [comment] 2022-06-08 01:00
Btw it happens with any way of a hurricane/tornado
Being summoned

**Comment by Dovahkiin-Warrior** [comment] 2022-06-08 01:40
> Btw it happens with any way of a hurricane/tornado Being summoned

@Jaytv25 Can you please load up single player, hit F3, press F2, then upload the screenshot here? You can link it on imgur or just drag your image into the reply box on this issue. That will give us the information we need to better understand the situation. Thanks!

**Comment by Mrbt0907** [comment] 2022-08-17 02:21
This hopefully is fixed in the next update 2.8. Please reopen this if the issue persists in the new update.

**Closed by Mrbt0907** 2022-08-17 02:21 UTC
Labels: Bug, Important

**Comment by Jaytv25** [comment] 2022-09-14 18:21
btw i just came back after a break

**Comment by Mrbt0907** [comment] 2022-09-14 19:00
What system are you running?

**Comment by Jaytv25** [comment] 2022-09-15 03:34
Geforce RTX

**Comment by Jaytv25** [comment] 2022-09-15 18:39
alright so i went to the new Indev version to see if it was fixed and...

https://drive.google.com/file/d/1y52qzbILyYtLPsKnd9QZWK8DqK3qaj9p/view?usp=sharing

i don't get why it happens

**Comment by Jaytv25** [comment] 2022-09-15 18:48
i picked the default recommended from 2020 for forge 1.12.2 since i did not think of downloading the same thing but a different version

**Comment by Jaytv25** [comment] 2022-09-15 18:49
i hope my comment did not come out confusing

**Comment by Jaytv25** [comment] 2022-09-15 18:51
even with the recommended forge version it does not work at all and i just tried it right now on 2:51 PM USA time

**Comment by Jaytv25** [comment] 2022-09-15 18:53
that is the exact version i was running

**Comment by ProfessorFartsalot** [comment] 2022-09-15 18:53
Are you still using coroutil 1.2.36 or did you upgrade to 1.2.37?

**Comment by ProfessorFartsalot** [comment] 2022-09-15 18:55
I have reviewed your proof file, this is very strange.  With forge build 2860 and coroutil 1.2.37 you should have no issues with the latest weather2 remastered release. I've tested it on nvidia and intel systems to be flawless.

**Comment by ProfessorFartsalot** [comment] 2022-09-15 18:56
Have you tried deleting your `%appdata%\.minecraft\config\weather2` folder yet to reset all configuration to default?

**Comment by Jaytv25** [comment] 2022-09-15 19:05
imma try that

**Comment by Jaytv25** [comment] 2022-09-15 19:07
IT WORKS

**Comment by Jaytv25** [comment] 2022-09-15 19:07
HOLY SHOOT

**Comment by Jaytv25** [comment] 2022-09-15 19:08
i guess that means its just because of the original 1.11.2 weather mod config mixing with remastered one

**Comment by Jaytv25** [comment] 2022-09-15 19:12
this also fixed another issue i had where the storms will never evolve beyond Hail

**Comment by ProfessorFartsalot** [comment] 2022-09-15 20:33
Yeah it is known that the weather2 original config is not compatible with weather2 remastered. This should be fixed in a future update where the EZGUI uses NBT data instead of the old CFG files.

**Comment by Mrbt0907** [comment] 2022-09-15 23:23
That is because the chance to become supercells and hailstorms are too high. Try lowering their value and raising the chances for tornados and cyclones.

**Comment by ProfessorFartsalot** [comment] 2022-09-15 23:26
OP already solved it, weather 2 original config handled it differently I believe. Default values fixed it.

**Comment by Jaytv25** [comment] 2022-09-16 00:28
why does F0 not exist?

**Comment by Mrbt0907** [comment] 2022-09-16 00:28
Is it spawning hailstorms?

**Comment by Jaytv25** [comment] 2022-09-16 00:29
nope it is doing rainstorm

**Comment by Mrbt0907** [comment] 2022-09-16 00:29
Try Ef0

**Comment by ProfessorFartsalot** [comment] 2022-09-16 00:29
It does. It's the rotating super cell with high wind and hail. A f0 tornado does not touch the ground and the rotating supercell with high wind can be classified as a f0.

**Comment by Jaytv25** [comment] 2022-09-16 00:29
that does the same thing

**Comment by Jaytv25** [comment] 2022-09-16 00:30
all it does is spawn generic rain

**Comment by Jaytv25** [comment] 2022-09-16 00:30
no cell or anything just rain

**Comment by Mrbt0907** [comment] 2022-09-16 00:31
Okay, so you are encountering an issue I fixed in the next update. The command is sometimes a bit broken. I'll try to finish the next indev as soon as I can.
