### ISSUE TITLE
Pollution of the Realms compatibility broken

### ISSUE THREAD

**Issue by Gliese-832-c** [Mrbt0907/Weather2-Remastered#109] opened 2022-11-15 21:04 UTC
It looks like Weather2-Remastered breaks Weather2's compatibility with the Pollution of the Realms mod.
```
java.lang.NoClassDefFoundError: weather2/api/WindDataHelper
    at com.endertech.minecraft.forge.world.ForgeWorld.getWindAt(ForgeWorld.java:92)
    at com.endertech.minecraft.mods.adpother.blocks.GasEmission.pushedByWind(GasEmission.java:681)
    at com.endertech.minecraft.mods.adpother.blocks.GasEmission.randomTick(GasEmission.java:670)
    at net.minecraft.world.WorldServer.updateBlocks(WorldServer.java:476)
    at net.minecraft.world.WorldServer.tick(WorldServer.java:225)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:756)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.ClassNotFoundException: weather2.api.WindDataHelper
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
    ... 10 more
Caused by: java.lang.NullPointerException
```

**Comment by Mrbt0907** [comment] 2022-11-15 21:08
Duplicate of #86. I cannot fix this on my end.

**Closed as completed by Mrbt0907** 2022-11-15 21:08 UTC
Labels: Bug, Duplicate, Wont Add/Cannot Fix, Confirmed

**Comment by Gliese-832-c** [comment] 2022-11-15 21:11
I apologize for the duplicate. I searched for similar issues, but saw none with "Pollution of the Realms" or "PotR" in the title so I thought that I'm in the clear.

**Comment by CosmicHikari** [comment] 2022-11-15 21:12
That's all good! The project domain changed with W2R, once 2.8 comes out, POTR can add support for the new version.
