### ISSUE TITLE
9999 Cold and warm fronts bug, however there are 0 storms in fact...

### ISSUE THREAD

**Issue by BroGames123** [Mrbt0907/Weather2-Remastered#149] opened 2023-06-21 15:27 UTC
Hello there!

Just now, I've launched minecraft and encountered the bug wich you may see on the photo linked to this bug report post.

There were like 3123123213123 cold and storm fronts visible on the radar when I placed it (pulse doppler radar), so I decided to write a "/storm kill all" command, but it has said in the chat that there are currently 0 storms active (however other than those millions of CF and WF on the radar, I saw clouds and storms too), and I couldn't read the radar normally, it just messed up cause of invisible cold and warm fronts... Wich didn't even exist in the world currently, in fact...

![2023-06-21_18 21 28](https://github.com/Mrbt0907/Weather2-Remastered/assets/136973381/809bc07e-04f5-4e2b-9b4a-fea25daa6477)

**Comment by BroGames123** [comment] 2023-06-21 15:29
Other mods were launched too, together with your mod:
1. Apple Core
2. coroutil
3. Cubic Chunks mod
4. Cubic World gen
5. Hunger in Peace
6. Optifine HD u G5
7. Terra Plus Plus mod
8. Weather2 Remastered
9. XL food mod

**Comment by BroGames123** [comment] 2023-06-21 15:34
PROBABLY FIXED!

The mod might be incompatible with three other mods I used with "Weather2 Remastered":
- Cubic Chunks mod
- Cubic World gen
- Terra Plus Plus mod

Or it could be incompatible with:
- Optifine HD u G5

I removed these mods, and all worked OK after I did so. Dunno if the first three of them were the problem, or the OptiFine ones, but still

**Comment by CosmicHikari** [comment] 2023-06-21 16:53
This is mainly caused by having weather enabled in other dimensions, though there could still be incompatible mods. Optifine does not cause this issue. If you can narrow it down to a mod that would be great.

**Comment by Mrbt0907** [comment] 2023-06-21 20:36
What remastered version are you playing with?

**Comment by BroGames123** [comment] 2023-06-26 18:03
> What remastered version are you playing with?

Hi, sorry for the late response
I'm playing with "Weather2Remastered-1.12.2-2.8.5.7-alpha.jar" actually

**Comment by CosmicHikari** [comment] 2023-06-26 18:18
Does re adding the removed mods bring this issue back?

**Comment by Mrbt0907** [comment] 2023-06-26 18:30
I'll hunt this bug down as it's even in the latest versions. I think I know why this is happening. I'll get back to you when I fix this

**Comment by Mrbt0907** [comment] 2023-06-29 02:57
Fixed in the next update

**Closed as completed by Mrbt0907** 2023-06-29 02:57 UTC
Labels: Bug, Important, Confirmed
